services:
  - type: web
    name: indian-law-bot
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
